name: html2md
description: Convert html to markdown in Dart.
version: 1.0.0
homepage: https://github.com/jarontai/html2md

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  html: ^0.14.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.5
